### PR TITLE
Various high priority bugs

### LINKED ISSUE #764: Default feed view was single column when I logged back into my account (make double column)

### LINKED ISSUE #793: No way to go back to expression center once you've selected an expression type - need a back button!

### LINKED ISSUE #818: Logging out takes you to a balck screen
Logging out of the app takes you to a black screen. 
- Latest Dev

### PR DESCRIPTION
**Pull request by Nash0x7E2**
This PR closes the following high priority issues raised by the team:
- Closes #793
- Closes #818
- Closes #764

### Misc 
- Added "route" method to welcome screen
- Fixed callback function in the confirmation dialog

### CODE REVIEW

File: lib/widgets/end_drawer/end_drawer.dart [hunk 1]
```diff
@@ -21,11 +22,16 @@ import 'package:provider/provider.dart';
...
+  _JuntoDrawerState createState() => _JuntoDrawerState();
+}
+
+class _JuntoDrawerState extends State<JuntoDrawer> {
+  Future<void> _onLogOut() async {
     try {
-      await context.bloc<AuthBloc>().add(LogoutEvent());
-      Navigator.popUntil(context, (r) => r.isFirst);
+      context.bloc<AuthBloc>().add(LogoutEvent());
+      Navigator.of(context).pushReplacement(Welcome.route());
```
Comment (orestesgaolin) [inline lib/widgets/end_drawer/end_drawer.dart:34]: I think this breaks login flow i.e. if you got to login or sign up it won't work

Comment (Nash0x7E2) [reply lib/widgets/end_drawer/end_drawer.dart:34]: Checked this, sign in, and sign up works fine. 

Going to the first route does not guarantee the user would be taken to the login screen since for some the first route would be the lotus screen.
